# Generated by Django 5.0.7 on 2024-07-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expenseshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseShare',
        ),
    ]
